### ISSUE TITLE
comments and suggestion

### ISSUE THREAD

**Issue by Yefeng0920** [jamessteeleii/Meta-Analysis-of-Variation-in-Resistance-Training#1]
Hi James (@jamessteeleii),
Well done in the R code. I (together with @itchyshin) carefully checked the code and posted some small comments and suggestions. But two of them probably need to be addressed. I briefly list my comments below (details see the corresponding R file).
- [x] We need to account for residual heterogeneity by intentionally adding `~ 1 | es`  as a random effect, as `metafor`  does not do this automatically. Otherwise, we are assuming that effects within studies are homogeneous, which is a very strong assumption
- [x] Strictly speaking, we also need to account for correlations/covariances in sampling errors because the dataset (at least) involves one of the situations causing dependence - multiple treatments (`arm`). But it is fine given that you use `robust()` to adjust the standard errors (and also 95% CIs). You do not need to do anything regarding this comment - just let you know this point
- [x] It seems that the formula to calculate the sampling variance of log response ratio (lnRR) is not correct (I checked it and referred to the papes where the correct formula came from). Shinichi was suggesting using `escalc()` for calculation rather than doing it manually
Shinichi (@itchyshin) might have some comments later (or might not). If I made any misleading comment, Shinichi will correct me.
Great job! @jamessteeleii

**Comment by jamessteeleii** [comment]
Hey Yefeng and Shinichi,

Thanks so much for going through it, and glad there was only a few things to address – gives me confidence in my coding ability 😊

I’ll get those things addressed, rerun the analyses and re-render the manuscript.

Let me know if either of you have any other comments on the code or manuscript. If you’re happy though, let me know and I’ll get it all sorted, pre-print and submit.

Thanks again for working with me on this – I think it will be a very important paper for our field.

James


From: Yefeng ***@***.***>
Sent: 13 October 2022 01:06
To: jamessteeleii/Meta-Analysis-of-Variation-in-Resistance-Training ***@***.***>
Cc: James Steele ***@***.***>; Mention ***@***.***>
Subject: [jamessteeleii/Meta-Analysis-of-Variation-in-Resistance-Training] comments and suggestion (Issue #1)


Hi James ***@***.***<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjamessteeleii&data=05%7C01%7Cjames.steele%40solent.ac.uk%7C5ef1370896ab4b58ede908daacaebb16%7Cd684e4cd491a4577bf33546478d72e3c%7C0%7C0%7C638012163711411737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VIDUuTf7IoWyfHJPPvJOfeOBeDw0FksmEJM%2B9bziaYg%3D&reserved=0>),
Well done in the R code. I (together with @itchyshin<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fitchyshin&data=05%7C01%7Cjames.steele%40solent.ac.uk%7C5ef1370896ab4b58ede908daacaebb16%7Cd684e4cd491a4577bf33546478d72e3c%7C0%7C0%7C638012163711411737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nTcEPvMcHFalLvAg15hj%2FY4Xmz9hSPWJfo%2ByZKuJkNk%3D&reserved=0>) carefully checked the code and posted some small comments and suggestions. But two of them probably need to be addressed. I briefly list my comments below (details see the corresponding R file).

  *   [ ] We need to account for residual heterogeneity by intentionally adding ~ 1 | es as a random effect, as metafor does not do this automatically. Otherwise, we are assuming that effects within studies are homogeneous, which is a very strong assumption
  *   [ ] Strictly speaking, we also need to account for correlations/covariances in sampling errors because the dataset (at least) involves one of the situations causing dependence - multiple treatments (arm). But it is fine given that you use robust() to adjust the standard errors (and also 95% CIs). You do not need to do anything regarding this comment - just let you know this point
  *   [ ] It seems that the formula to calculate the sampling variance of log response ratio (lnRR) is not correct (I checked it and referred to the papes where the correct formula came from). Shinichi was suggesting using escalc() for calculation rather than doing it manually
Shinichi ***@***.***<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fitchyshin&data=05%7C01%7Cjames.steele%40solent.ac.uk%7C5ef1370896ab4b58ede908daacaebb16%7Cd684e4cd491a4577bf33546478d72e3c%7C0%7C0%7C638012163711411737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nTcEPvMcHFalLvAg15hj%2FY4Xmz9hSPWJfo%2ByZKuJkNk%3D&reserved=0>) might have some comments later (or might not). If I made any misleading comment, Shinichi will correct me.
Great job! @jamessteeleii<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjamessteeleii&data=05%7C01%7Cjames.steele%40solent.ac.uk%7C5ef1370896ab4b58ede908daacaebb16%7Cd684e4cd491a4577bf33546478d72e3c%7C0%7C0%7C638012163711411737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VIDUuTf7IoWyfHJPPvJOfeOBeDw0FksmEJM%2B9bziaYg%3D&reserved=0>

**Comment by itchyshin** [comment]
@jamessteeleii 

Please go ahead and incorprate @Yefeng0920 's comments and why don't I give the final check both for the code and MS.

Thanks!

@itchyshin

**Comment by jamessteeleii** [comment]
@itchyshin no problem - will do!

Just a quick one - I redid the variance on the lnRR using Marc's formula as opposed to Morris'. It now looks a bit more realistic with ~33% between study variance. When plotting though the exponentiated results have very small CIs on individual estimates which looks a bit odd. I've attached both exp and ln RR plots. Which do you think would be best to use? I think that maybe the lnRR plot and then maybe just include the exponentiated results in the text for interpretability? Or could plot them in a patchwork all together.

Thanks,

@jamessteeleii 
[Exp lnRR.pdf](https://github.com/jamessteeleii/Meta-Analysis-of-Variation-in-Resistance-Training/files/9808363/Exp.lnRR.pdf)
[lnRR.pdf](https://github.com/jamessteeleii/Meta-Analysis-of-Variation-in-Resistance-Training/files/9808364/lnRR.pdf)

**Comment by jamessteeleii** [comment]
Oop - just noticed the text is incorrect in the lnRR plot so ignore that

**Comment by jamessteeleii** [comment]
Ok, so I've adressed all of @Yefeng0920 great comments and just pushed the changes to the analysis code, models, plots etc. along with a re-rendered manuscript. I also updated the manuscript with trackdown so the googledoc version is up to date if you want to make any changes to it directly when giving it a final lookover @itchyshin (https://docs.google.com/document/d/1n_ww3WBWbiPwt8RbNqWhY8rJ7jmmX-37CB9dFbgmmHI/edit).

Thanks again for both your support and input!

I've not used the 'issues' thing before but I guess when you are both happy with things you are able to Close it with comment?

@jamessteeleii

**Comment by itchyshin** [comment]
@jamessteeleii - I will get back to you on this by Monday, if not earlier. (and once done - yes, I can close the issue - even closing it we can still see it and you can reopen if necessary. But I usually create a new issue)

**Comment by itchyshin** [comment]
@jamessteeleii - sorry it took me so long to get back (several urgent things I had to deal with). I got a bit confused with the text formulas and code formulas are different but you explain this in the footnote, so it is all good. I did not have any further comments (at least a big one). The text reads well. Let's see what referees would say - Thanks! (@itchyshin)

**Comment by jamessteeleii** [comment]
@itchyshin no problem at all! Thanks so much for going over it again. I'll get it pre-printed and submit to Journal of Sports Sciences over the next day or so. Fingers crossed!
